apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: hello-job
spec:
  completions: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: hello-job
        resources: {}
        command:
        - echo
        - Hello I am from job
      restartPolicy: Never
status: {}
