apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "5"
    deployment.kubernetes.io/max-replicas: "7"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-06-17T10:23:18Z"
  generation: 1
  labels:
    app: webapp
    pod-template-hash: 6684ccd7b8
  name: webapp-6684ccd7b8
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: webapp
    uid: ec4832a4-a818-48db-8d12-3cb9e77e66e5
  resourceVersion: "765286"
  uid: 0ddeb38a-4191-4907-94c6-dd7d31951a0e
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp
      pod-template-hash: 6684ccd7b8
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
        pod-template-hash: 6684ccd7b8
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  fullyLabeledReplicas: 5
  observedGeneration: 1
  readyReplicas: 5
  replicas: 5
