apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-06-17T10:23:18Z"
  generateName: webapp-6684ccd7b8-
  labels:
    app: webapp
    pod-template-hash: 6684ccd7b8
  name: webapp-6684ccd7b8-wxwvl
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: webapp-6684ccd7b8
    uid: 0ddeb38a-4191-4907-94c6-dd7d31951a0e
  resourceVersion: "765271"
  uid: 9189956a-01bc-4feb-af8e-06ac9c78e054
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-c9v8m
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3d-k3s-default-server-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-c9v8m
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-06-17T10:23:18Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-06-17T10:23:20Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-06-17T10:23:20Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-06-17T10:23:18Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://a22867fb19cc362a4b2e1593bcd1f5b73e701d4331d0d795238cfaa3eeb013f9
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:593dac25b7733ffb7afe1a72649a43e574778bf025ad60514ef40f6b5d606247
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-06-17T10:23:20Z"
  hostIP: 172.22.0.2
  phase: Running
  podIP: 10.42.0.94
  podIPs:
  - ip: 10.42.0.94
  qosClass: BestEffort
  startTime: "2023-06-17T10:23:18Z"