apiVersion: v1
kind: Pod
metadata:
  name: "messaging"
  namespace: default
  labels:
    app: "messaging"
    tier: "msg"
spec:
  containers:
  - name: messaging
    image: "redis:alpine"
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
    - containerPort: 6379
      name:  http