apiVersion: v1
kind: Pod
metadata:
  name: "static-busybox"
  namespace: default
  labels:
    app: "static-busybox"
spec:
  containers:
  - name: static-busybox
    image: "busybox"
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    command: ["/bin/sh"]
    args: ["-c", "sleep 1000"]