apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
  #namespace: pvc-demo
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-claim
    #namespace: pvc-demo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec-igor
spec:
  containers:
    - image: nginx
      name: use-pv
      volumeMounts:
        - mountPath: /tmp
          name: my-pod-volume
      resources: {}
  volumes:
    - name: my-pod-volume
      persistentVolumeClaim:
        claimName: my-volume-claim

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}


