apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"nginx-deploy","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx-deploy"}},"template":{"metadata":{"labels":{"app":"nginx-deploy"}},"spec":{"containers":[{"image":"nginx:1.16","imagePullPolicy":"Always","name":"nginx-deploy","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"100m","memory":"128Mi"}}}]}}}}
    kubernetes.io/change-cause: kubectl set image deployment/nginx-deploy nginx-deploy=nginx:1.17
      --record=true
  creationTimestamp: "2023-06-10T13:55:16Z"
  generation: 2
  name: nginx-deploy
  namespace: default
  resourceVersion: "644855"
  uid: 8f3d751d-c583-44d7-8468-cd80be983d40
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy
    spec:
      containers:
      - image: nginx:1.17
        imagePullPolicy: Always
        name: nginx-deploy
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-06-10T13:55:16Z"
    lastUpdateTime: "2023-06-10T13:55:16Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-06-10T13:55:16Z"
    lastUpdateTime: "2023-06-10T13:55:16Z"
    message: ReplicaSet "nginx-deploy-6d6cf97585" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
