apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  labels:
    name: nginx-resolver
    svcselector: nginx-resolver
spec:
  containers:
  - name: nginx-resolver
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-service
spec:
  selector:
    svcselector: nginx-resolver
  ports:
  - port: 80
    targetPort: 80


