apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    name: multi-pod
spec:
  containers:
  - name: alpha
    image: nginx
    env:
      - name: alpha
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - name: beta
    image: busybox
    env:
      - name: beta
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    command: ["/bin/sh"]
    args: ["-c", "sleep 4800"]